### PR TITLE
Add colon to regex after file|http|https match to avoid mismatches where...

### PR DESCRIPTION
**Pull request by PlainSight**
... site domain contains the string 'file'

### CODE REVIEW

**Comment by niemyjski** [comment]
@PlainSight, devinhode2 , I'm helping manage the TraceKit project. Can you please create a pull request for this here https://github.com/csnover/TraceKit so we can get it merged in.

**Comment by devinrhode2** [comment]
By the amount of Notifications maybe we should do some pair progeamming
sometime..

**Comment by niemyjski** [comment]
I'd be down for that.. Do you have skype?

**Comment by devinrhode2** [comment]
Yep, same username. Checkout floobits if you want to use that

Hmm.. dont know any good times that work off hand, but checkout my shieldjs

**Comment by niemyjski** [comment]
@PlainSight, this has been fixed in the v0.2.0 release here: https://github.com/csnover/TraceKit

**Pull request closed without merging**
